import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'services/auth_service.dart';
import 'services/property_service.dart';
import 'services/location_service.dart';
import 'utils/theme.dart';
import 'utils/constants.dart';
import 'views/home/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Note: This will fail if google-services.json/GoogleService-Info.plist are missing.
  // We'll wrap it in a try-catch to allow the app to run (for UI testing) if possible,
  // though Firebase features won't work.
  try {
    // For Windows, Web and other platforms, you should use DefaultFirebaseOptions.currentPlatform
    // which is generated by the FlutterFire CLI (flutterfire configure).
    await Firebase.initializeApp();
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
    debugPrint('If you are running on Windows, make sure you have run "flutterfire configure"');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
        Provider<PropertyService>(create: (_) => PropertyService()),
        Provider<LocationService>(create: (_) => LocationService()),
        StreamProvider(
          create: (context) => context.read<AuthService>().user,
          initialData: null,
        ),
      ],
      child: MaterialApp(
        title: AppConstants.appName,
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        builder: (context, child) {
          return Column(
            children: [
              if (Firebase.apps.isEmpty)
                Container(
                  color: Colors.orange,
                  width: double.infinity,
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  child: const Material(
                    color: Colors.transparent,
                    child: Text(
                      'Firebase not initialized. Run "flutterfire configure"',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.white, fontSize: 12),
                    ),
                  ),
                ),
              Expanded(child: child!),
            ],
          );
        },
        home: const HomeScreen(),
      ),
    );
  }
}
